import type { Metadata } from "next";
import "./globals.css";

import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import Header from "./layout/header";
import { Providers } from "./layout/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {locale}
}: {
    children: React.ReactNode;
    params: {locale: string};
  }) {
    const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning >
      <body className={`antialiased bg-gray-50 dark:bg-slate-800`}>
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <Header />
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
